---

parserOptions:
  ecmaVersion: 8
  sourceType: module

env:
  browser: true
  node: true

plugins:
  - vue

extends:
  - eslint:recommended
  - plugin:vue/recommended

rules:
  no-unused-vars: 'off'
  no-console: 'off'
  no-empty: 'off'
